<!-- Code example for php using Laravel framework
This code was generated by chatGPT from pseudo-code
If you spot an issue, feel free to create a PR to fix it -->

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Hash;

class SlackEventsController extends Controller
{
    public function verifySlackRequest(Request $request)
    {
        $timestamp = $request->header('X-Slack-Request-Timestamp');
        $slackSignature = $request->header('X-Slack-Signature');

        if (is_null($timestamp) || is_null($slackSignature)) {
            return false;
        }

        $signingBaseString = 'v0:' . $timestamp . ':' . $request->getContent();
        // TODO replace YOUR_SLACK_SIGNING_SECRET with your own secret
        $mySignature = 'v0=' . hash_hmac('sha256', $signingBaseString, YOUR_SLACK_SIGNING_SECRET);

        return hash_equals($mySignature, $slackSignature);
    }

    public function slackEventsView(Request $request)
    {
        if (!$this->verifySlackRequest($request)) {
            return response()->json(['error' => 'Unauthorized'], 403);
        }

        $challenge = $request->input('challenge');

        if ($challenge) {
            return response($challenge);
        }

        $response = null;
        // TODO: Implement your custom flow here
        // $response = $this->handleSlackEvent($request->all());

        return response($response);
    }
}