// Code example for node.js using Express.js framework
// This code was generated by chatGPT from pseudo-code
// If you spot an issue, feel free to create a PR to fix it

const express = require('express');
const crypto = require('crypto');

const app = express();

function verifySlackRequest(req) {
    const timestamp = req.headers['x-slack-request-timestamp'];
    const slackSignature = req.headers['x-slack-signature'];
    if (!timestamp || !slackSignature) {
        return false;
    }
    const signingBaseString = `v0:${timestamp}:${req.body}`;
    // TODO replace YOUR_SLACK_SIGNING_SECRET with your own secret
    const mySignature = 'v0=' + crypto.createHmac('sha256', 'YOUR_SLACK_SIGNING_SECRET')
        .update(signingBaseString)
        .digest('hex');
    return crypto.timingSafeEqual(Buffer.from(mySignature), Buffer.from(slackSignature));
}

app.post('/slack-events', (req, res) => {
    if (!verifySlackRequest(req)) {
        return res.status(403).end();
    }
    const challenge = req.body.challenge;
    if (challenge) {
        return res.send(challenge);
    }
    let response = null;
    // TODO: implement your custom flow here
    // response = handleSlackEvent(req.body);
    return res.send(response);
});